### ISSUE TITLE
Doc: Update / Upgrade documentation

### ISSUE THREAD

**Issue by Tykok** [Tykok/cedict-chinese-transformation#137]
### Tell us if you know the size of this feature.

Medium, it will take some times 🙌🏽

### Expecting for this feature 🚀

Update / Upgrade the documentation of the project to explain exactly how can we use it

### Code of Conduct 😇

- [X] I agree to follow this project's Code of Conduct

**Comment by hockyy** [comment]
this repo is underrated. :O thanks! I'm thinking of using this for my future projects
