### ISSUE TITLE
Fix:  some of the dictionary entries are malformed, only having first character's pinyin

### ISSUE THREAD

**Issue by dengel29** [Tykok/cedict-chinese-transformation#154]
### OS 🔎

Mac

### Node Version 📦

v19.9.0

### Npm or Yarn Version 📦

pnpm 8.10.5

### Severity / Criticality of the bug(s) 👀

High

### What happened ❓

I noticed this bug when calling `getByTraditional`, and reading the pinyin output. When getting the pinyin output, only the first character in a multi-character phrase will have its pinyin returned. This does not appear to be an issue with parsing the response, but with the dictionary itself. Here is an example entry from `cedict.json`

```json
{
"traditional":"傍晚",
"simplified":"傍晚",
"pinyin":"bang4",
"english":["in the evening","when night falls","towards evening","at night fall","at dusk"]
}
```

There are many such entries.

### Contact Details 📫

dan@dngl.cc

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Tykok** [comment]
Sorry, I didn't really take the time to correct this error. Thanks for this ticket 🙌🏽
